name: Docker Build

on:
  push:
    branches:
    - main
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: 'Build:dockerimage'
        uses: docker/build-push-action@v1
        with:
          registry: docker.pkg.github.com
          build_args: CONTENTFUL_SPACE_ID=${{secrets.CONTENTFUL_SPACE_ID}},CONTENTFUL_ACCESS_TOKEN=${{secrets.CONTENTFUL_ACCESS_TOKEN}}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
          repository: ${{ github.repository }}/web
          tags: ${{ github.sha }}
